apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: production-green
  region: ap-northeast-1
  version: "1.20"

vpc:
  id: vpc-00f9c21cc545698cc
  subnets:
    public:
      ap-northeast-1a:
          id: subnet-0c83cd432fa467b31
      ap-northeast-1c:
          id: subnet-0dc667c51fdc84788
    private:
      ap-northeast-1a:
          id: subnet-0c589a09a32f7e034
      ap-northeast-1c:
          id: subnet-02c3b6cda10c09211

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true