apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: production
  region: ap-northeast-1
  version: "1.23"

vpc:
  id: vpc-0a2c4bbecb3cf929a
  subnets:
    public:
      ap-northeast-1a:
          id: subnet-032eb505beae31782
      ap-northeast-1c:
          id: subnet-0e652912ce2814ebb
    private:
      ap-northeast-1a:
          id: subnet-07df8cee98c2af067
      ap-northeast-1c:
          id: subnet-0716a9999a3202d4e

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
