apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: staging-green
  region: ap-northeast-1

managedNodeGroups:
  - name: managed-ng-1
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    ssh:
      enableSsm: true
    privateNetworking: true
