apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: staging
  region: ap-northeast-1
  version: "1.23"

vpc:
  id: vpc-06ca05f948c53c581
  subnets:
    public:
      ap-northeast-1a:
          id: subnet-00ba83d23f5cac84b
      ap-northeast-1c:
          id: subnet-027ac364f59b41170
    private:
      ap-northeast-1a:
          id: subnet-0732433774c76279a
      ap-northeast-1c:
          id: subnet-08460b3c7a1cdcdcc

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
