apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: staging
  region: ap-northeast-1
vpc:
  cidr: "10.1.0.0/16"

availabilityZones:
  - ap-northeast-1a
  - ap-northeast-1c

managedNodeGroups:
  - name: managed-ng-1
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    ssh:
      allow: true
      publicKeyName: XXXX_KEY_PAIR_NAME_XXXX
    privateNetworking: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
