apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
imagePullSecrets:
- name: dockerhub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-dex-server
imagePullSecrets:
- name: dockerhub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-redis
imagePullSecrets:
- name: dockerhub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
imagePullSecrets:
- name: dockerhub
