apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-ingress-controller
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: alb-ingress-controller/overlays/staging
    repoURL: ssh://XXXX_SSH_KEY_ID_XXXX@git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/infra
  syncPolicy:
    automated: {}
