apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  destination:
    namespace: backend
    server: https://kubernetes.default.svc
  project: default
  source:
    path: backend/overlays/staging
    repoURL: ssh://XXXX_SSH_KEY_ID_XXXX@git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
