apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  project: default
  source:
    repoURL: https://github.com/godaddy/kubernetes-external-secrets.git
    path: charts/kubernetes-external-secrets
    helm:
      releaseName: external-secrets
      parameters:
      - name: env.AWS_DEFAULT_REGION
        value: ap-northeast-1
      - name: env.AWS_REGION
        value: ap-northeast-1
      - name: fullnameOverride
        value: external-secrets
      - name: serviceAccount.name
        value: external-secrets
      - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: arn:aws:iam::XXXX_AWS_ACCOUNT_ID_XXXX:role/external-secrets-staging
      - name: securityContext.fsGroup
        value: "65534"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
