apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: frontend
    server: https://kubernetes.default.svc
  project: default
  source:
    path: frontend/overlays/staging
    repoURL: ssh://XXXX_SSH_KEY_ID_XXXX@git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/infra
  syncPolicy:
    automated: {}
