AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  CodeBuildProjectName:
    Description: CodeBuild project name
    Type: String
  CodePipelineArtifactStoreBucketName:
    Description: CodePipeline artifact store bucket name
    Type: String
  DockerHubSecret:
    Description: Secret ARN for Docker Hub
    Type: String

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CodeBuildServiceRole-${CodeBuildProjectName}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
        - arn:aws:iam::aws:policy/AWSCodeCommitPowerUser
      Policies:
        - PolicyName: CodeBuildBasePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildProjectName}
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildProjectName}:*
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource:
                  - !Sub arn:aws:s3:::${CodePipelineArtifactStoreBucketName}
                  - !Sub arn:aws:s3:::${CodePipelineArtifactStoreBucketName}/*
              - Effect: Allow
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                Resource:
                  - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${CodeBuildProjectName}-*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:dockerhub-*
              - Effect: Allow
                Action:
                  - securityhub:BatchImportFindings
                Resource:
                  - !Sub arn:aws:securityhub:${AWS::Region}::product/aquasecurity/aquasecurity
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        EncryptionDisabled: false
        Name: !Ref CodeBuildProjectName
        Packaging: NONE
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: DOCKERHUB_USER
            Type: SECRETS_MANAGER
            Value: !Sub ${DockerHubSecret}:username
          - Name: DOCKERHUB_PASS
            Type: SECRETS_MANAGER
            Value: !Sub ${DockerHubSecret}:password
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          Status: DISABLED
      Name: !Ref CodeBuildProjectName
      ServiceRole: !GetAtt [CodeBuildServiceRole, Arn]
      Source:
        Type: CODEPIPELINE
