AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  CodeBuildArtifactStoreBucketName:
    Description: CodeBuild artifact store bucket name
    Type: String

Resources:
  CodeBuildArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CodeBuildArtifactStoreBucketName
  CodeBuildArtifactStoreBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CodeBuildArtifactStoreBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: s3:PutObject
            Resource:
              !Sub ${CodeBuildArtifactStoreBucket.Arn}/*
            Condition:
              StringNotEquals:
                "s3:x-amz-server-side-encryption": "aws:kms"
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              !Sub ${CodeBuildArtifactStoreBucket.Arn}/*
            Condition:
              Bool:
                "aws:SecureTransport": false