AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ClusterName:
    Description: EKS cluster name
    Type: String
  NamespaceName:
    Description: Namespace name
    Type: String
  ServiceAccountName:
    Description: Service Account name
    Type: String
  OidcProvider:
    Description: OIDC Provider
    Type: String

Resources:
  FluentBitRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub fluent-bit-${ClusterName}
      AssumeRolePolicyDocument:
        !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${OidcProvider}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "${OidcProvider}:sub": "system:serviceaccount:${NamespaceName}:${ServiceAccountName}"
                  }
                }
              }
            ]
          }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
