apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: backend
  namespace: backend
spec:
  backendType: secretsManager
  data:
  - key: mydb/hogehoge
    name: username
    property: username
