apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  source:
    targetRevision: main
    path: namespaces/overlays/staging
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  source:
    targetRevision: main
    path: frontend/overlays/staging
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  source:
    targetRevision: main
    path: backend/overlays/staging
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  source:
    targetRevision: main
    path: aws-load-balancer-controller/overlays/staging
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  source:
    targetRevision: main
    path: cert-manager/overlays/staging
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  source:
    targetRevision: main
    path: argocd/overlays/staging
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  source:
    targetRevision: main
    path: metrics-server/overlays/staging
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-insights
  namespace: argocd
spec:
  source:
    targetRevision: main
    path: container-insights/overlays/staging
