apiVersion: v1
kind: Namespace
metadata:
  labels:
    admission.gatekeeper.sh/ignore: no-self-managing
    control-plane: controller-manager
    gatekeeper.sh/system: "yes"
  name: gatekeeper-system
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dockerhub
  namespace: gatekeeper-system
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: dockerconfigjson
      name: .dockerconfigjson
