apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8spspprivilegedcontainer
spec:
  crd:
    spec:
      names:
        kind: K8sPSPPrivilegedContainer
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8spspprivileged

        violation[{"msg": msg, "details": {}}] {
          c := input_containers[_]
          c.securityContext.privileged
          msg := sprintf("Privileged container is not allowed: %v, securityContext: %v", [c.name, c.securityContext])
        }

        # Podの場合
        input_containers[c] {
          c := input.review.object.spec.containers[_]
        }
        input_containers[c] {
          c := input.review.object.spec.initContainers[_]
        }

        # Deployment, StatefulSet, DaemonSet, Jobの場合
        input_containers[c] {
          c := input.review.object.spec.template.spec.containers[_]
        }
        input_containers[c] {
          c := input.review.object.spec.template.spec.initContainers[_]
        }

        # CronJobの場合
        input_containers[c] {
          c := input.review.object.spec.jobTemplate.spec.template.spec.containers[_]
        }
        input_containers[c] {
          c := input.review.object.spec.jobTemplate.spec.template.spec.initContainers[_]
        }
