apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPPrivilegedContainer
metadata:
  name: psp-privileged-container
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds:
          ["Deployment", "Pod", "CronJob", "Job", "StatefulSet", "DaemonSet"]
    excludedNamespaces: ["kube-system"]
    # labelSelector:
    #   matchExpressions:
    #     - key: k8s-app
    #       operator: NotIn
    #       values:
    #         - kube-proxy
    #         - aws-node
